// config/roles.js
export const ROLES = {
  ADMIN: 'admin',
  MANAGER: 'manager',
  PREMIUM_USER: 'premium_user',
  USER: 'user'
};

export const PERMISSIONS = {
  // User permissions
  CREATE_USER: 'create_user',
  READ_USER: 'read_user',
  UPDATE_USER: 'update_user',
  DELETE_USER: 'delete_user',

  // Subscription permissions
  CREATE_SUBSCRIPTION: 'create_subscription',
  READ_SUBSCRIPTION: 'read_subscription',
  UPDATE_SUBSCRIPTION: 'update_subscription',
  DELETE_SUBSCRIPTION: 'delete_subscription',
  MANAGE_ALL_SUBSCRIPTIONS: 'manage_all_subscriptions',

  // Admin permissions
  MANAGE_USERS: 'manage_users',
  VIEW_ANALYTICS: 'view_analytics',
  SYSTEM_CONFIG: 'system_config',

  // Rate limiting permissions
  VIEW_RATE_LIMIT_STATS: 'view_rate_limit_stats',
  MANAGE_RATE_LIMITS: 'manage_rate_limits'
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.READ_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.CREATE_SUBSCRIPTION,
    PERMISSIONS.READ_SUBSCRIPTION,
    PERMISSIONS.UPDATE_SUBSCRIPTION,
    PERMISSIONS.DELETE_SUBSCRIPTION,
    PERMISSIONS.MANAGE_ALL_SUBSCRIPTIONS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.SYSTEM_CONFIG,
    PERMISSIONS.VIEW_RATE_LIMIT_STATS,
    PERMISSIONS.MANAGE_RATE_LIMITS
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.READ_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.CREATE_SUBSCRIPTION,
    PERMISSIONS.READ_SUBSCRIPTION,
    PERMISSIONS.UPDATE_SUBSCRIPTION,
    PERMISSIONS.DELETE_SUBSCRIPTION,
    PERMISSIONS.MANAGE_ALL_SUBSCRIPTIONS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_RATE_LIMIT_STATS
  ],
  [ROLES.PREMIUM_USER]: [
    PERMISSIONS.CREATE_SUBSCRIPTION,
    PERMISSIONS.READ_SUBSCRIPTION,
    PERMISSIONS.UPDATE_SUBSCRIPTION,
    PERMISSIONS.DELETE_SUBSCRIPTION,
    PERMISSIONS.READ_USER,
    PERMISSIONS.VIEW_RATE_LIMIT_STATS
  ],
  [ROLES.USER]: [
    PERMISSIONS.CREATE_SUBSCRIPTION,
    PERMISSIONS.READ_SUBSCRIPTION,
    PERMISSIONS.UPDATE_SUBSCRIPTION,
    PERMISSIONS.READ_USER,
    PERMISSIONS.VIEW_RATE_LIMIT_STATS
  ]
};
